Added check for directory
Diosa34/DMS-HelloWorld pull request #5
Opened 2022-04-10 12:23 UTC by Diosa34

Checking if user's file is not a directory

2022-04-10 14:12 UTC, seductorAmadeus commented on src/main/kotlin/commands/Functions.kt
> +                    if (i != t-1) {
Please reduce duplicated code :)

2022-04-10 14:37 UTC, Diosa34 commented on src/main/kotlin/commands/Functions.kt
> +                    if (i != t-1) {
Done

2022-04-15 18:21 UTC, seductorAmadeus requested changes

2022-04-15 18:21 UTC, seductorAmadeus commented on src/main/java/com/github/Diosa34/DMS_HelloWorld/classes/Vehicle.java
> +        int max_id = 0;
Replace max_id with maxId

2022-04-15 18:21 UTC, seductorAmadeus commented on src/main/java/com/github/Diosa34/DMS_HelloWorld/parsing/CommandExecuter.java
> +    private Application applicationInstance;
Add final modifier here

2022-04-15 18:21 UTC, seductorAmadeus commented on src/main/java/com/github/Diosa34/DMS_HelloWorld/Application.java
> +}
Please add javadoc

2022-04-29 23:33 UTC, merged